default_motd: '&7Welcome to the &amyserver.com &7!' # デフォルトで表示される Motd
player_motd: '&7Welcome to the &a%virtual_hostname%&7, &e%player_name% &7!' #プレイヤー別に表示される仮想 Motd
player_favicon_enabled: false #プレイヤー別に表示される当該プレイヤーのヘッドアイコン表示有無